# Generated by Django 5.1.1 on 2024-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='projects.skills'),
        ),
    ]
