import "../globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import { ThemeDarkMode } from "@/providers/ThemeDarkMode";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="font-jetBrainsMono bg-gray-50 text-gray-900 dark:text-gray-50 dark:bg-gray-900">
        <ThemeDarkMode>
          <AuthProvider>
            <Header />
                {children}
            <Footer />
          </AuthProvider>
        </ThemeDarkMode>
      </body>
    </html>
  );
}
